name: Build & Deploy
on:
  push:
    branches:
      - main

env:
  SKIP_PREFLIGHT_CHECK: true

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Generate changelog
      uses: jaywcjlove/changelog-generator@v1.5.7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filter-author: (SunLxy|dependabot\[bot\]|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
        
    - run: yarn 
    - run: yarn build:ui 
    - run: yarn run docs:build

    - name: Create Doc
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs-dist

    - name: Create Tag
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.3.8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        package-path: ./package.json

    - name: Generate changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v1.5.7
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        head-ref: ${{steps.create_tag.outputs.version}}
        filter-author: (SunLxy|dependabot\[bot\]|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Create Release
      uses: ncipollo/release-action@v1
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ steps.create_tag.outputs.version }}
        tag: ${{ steps.create_tag.outputs.version }}
        body: |
          ```bash
          npm i carefree-antd@${{steps.create_tag.outputs.version}}
          npm i carefree-antd-form@${{steps.create_tag.outputs.version}}
          npm i carefree-antd-edit-table@${{steps.create_tag.outputs.version}}
          npm i carefree-antd-transfer-search@${{steps.create_tag.outputs.version}}
          npm i carefree-antd-transfer@${{steps.create_tag.outputs.version}}
          npm i carefree-pro-table@${{steps.create_tag.outputs.version}}
          npm i carefree-sortable@${{steps.create_tag.outputs.version}}
          npm i carefree-antd-transfer-search@${{steps.create_tag.outputs.version}}
          ```
          ${{ steps.changelog.outputs.compareurl }}
          ${{ steps.changelog.outputs.changelog }}

    # - uses: fregante/release-with-changelog@v3
    #   if: steps.create_tag.outputs.successful
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     name: ${{ steps.create_tag.outputs.tag }}
    #     tag: ${{ steps.create_tag.outputs.tag }}
    #     body: |
    #       ```bash
    #       npm i carefree-antd@${{steps.create_tag.outputs.version}}

    #       ```
    #       ${{ steps.changelog.outputs.compareurl }}
    #       ${{ steps.changelog.outputs.changelog }}

    # - run: npm install @jsdevtools/npm-publish -g
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/form/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/carefree-antd/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/sortable/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/edit-table/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/pro-table/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/fuzzy-query/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/transfer-search/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/transfer/package.json
    # - run: npm-publish --token="${{ secrets.NPM_TOKEN }}" ./packages/from-utils/package.json

    - name: Publish 🚀
      uses: SunLxy/npm-publish@main
      with:
        token: ${{ secrets.NPM_TOKEN }}
        cwd: packages
        files: |
        !store
        !request